// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX0itH_KRPRMvXqoXCJj4_MHL3ic-G_zQ',
    appId: '1:32825004702:ios:3b59173f7508abe86da18f',
    messagingSenderId: '32825004702',
    projectId: 'pictoflutterchat',
    databaseURL: 'https://pictoflutterchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pictoflutterchat.firebasestorage.app',
    iosBundleId: 'com.cbnoah.pictoFlutterChat',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRCwPFmj2Vo9xZPcI-_rymFWYWVJ5dAw',
    appId: '1:32825004702:android:383ff587b623dc636da18f',
    messagingSenderId: '32825004702',
    projectId: 'pictoflutterchat',
    databaseURL: 'https://pictoflutterchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pictoflutterchat.firebasestorage.app',
  );
}
